spring:
  data:
    mongodb:
      database: <your daatabase name>
      port: '27017'
      host: localhost
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <your client id>
            client-secret: <your client secret>
          facebook:
            clientId: <your client id>
            clientSecret: <your client secret>
#facebook:
#  scope: public_profile
  
SigningKey: <your jwt key>
